// Mock data for development — replace with Supabase queries later

export const mockClubs = [
    {
        id: '1',
        name: 'Tech Innovators',
        name_ar: 'المبتكرون التقنيون',
        description: 'A community of tech enthusiasts exploring cutting-edge technologies, hosting workshops, and building real-world projects together.',
        description_ar: 'مجتمع من عشاق التكنولوجيا يستكشفون أحدث التقنيات وينظمون ورش عمل ويبنون مشاريع واقعية معاً.',
        category: 'academic',
        logo_url: null,
        cover_url: null,
        member_count: 85,
        status: 'approved',
        created_at: '2025-09-01',
    },
    {
        id: '2',
        name: 'Sports Club',
        name_ar: 'النادي الرياضي',
        description: 'Encouraging healthy lifestyles through sports activities, tournaments, and fitness challenges for all students.',
        description_ar: 'تشجيع أنماط الحياة الصحية من خلال الأنشطة الرياضية والبطولات وتحديات اللياقة البدنية لجميع الطلاب.',
        category: 'sports',
        logo_url: null,
        cover_url: null,
        member_count: 120,
        status: 'approved',
        created_at: '2025-08-15',
    },
    {
        id: '3',
        name: 'Drama & Arts',
        name_ar: 'الدراما والفنون',
        description: 'Unleash your creativity through theater performances, art exhibitions, and creative workshops.',
        description_ar: 'أطلق إبداعك من خلال العروض المسرحية والمعارض الفنية وورش العمل الإبداعية.',
        category: 'cultural',
        logo_url: null,
        cover_url: null,
        member_count: 45,
        status: 'approved',
        created_at: '2025-09-10',
    },
    {
        id: '4',
        name: 'Volunteer Corps',
        name_ar: 'فيلق المتطوعين',
        description: 'Making a positive impact in Salalah through community service, charity drives, and environmental initiatives.',
        description_ar: 'إحداث تأثير إيجابي في صلالة من خلال خدمة المجتمع وحملات الخير والمبادرات البيئية.',
        category: 'community',
        logo_url: null,
        cover_url: null,
        member_count: 92,
        status: 'approved',
        created_at: '2025-08-20',
    },
    {
        id: '5',
        name: 'Photography Society',
        name_ar: 'جمعية التصوير',
        description: 'Capture the world through your lens. Photo walks, editing workshops, and exhibitions await.',
        description_ar: 'التقط العالم عبر عدستك. جولات تصوير وورش تحرير ومعارض بانتظارك.',
        category: 'cultural',
        logo_url: null,
        cover_url: null,
        member_count: 38,
        status: 'approved',
        created_at: '2025-10-01',
    },
    {
        id: '6',
        name: 'Robotics Lab',
        name_ar: 'مختبر الروبوتات',
        description: 'Design, build, and compete with robots. From Arduino to AI-powered machines.',
        description_ar: 'صمم وابنِ وتنافس بالروبوتات. من آردوينو إلى الآلات المدعومة بالذكاء الاصطناعي.',
        category: 'academic',
        logo_url: null,
        cover_url: null,
        member_count: 62,
        status: 'approved',
        created_at: '2025-09-15',
    },
]

export const mockEvents = [
    {
        id: '1',
        title: 'AI Workshop 2026',
        title_ar: 'ورشة الذكاء الاصطناعي 2026',
        description: 'Hands-on workshop covering machine learning fundamentals, neural networks, and practical applications using Python and TensorFlow.',
        description_ar: 'ورشة عملية تغطي أساسيات تعلم الآلة والشبكات العصبية والتطبيقات العملية باستخدام بايثون وتنسرفلو.',
        club_id: '1',
        club: { name: 'Tech Innovators', name_ar: 'المبتكرون التقنيون' },
        date: '2026-03-15T10:00:00',
        end_date: '2026-03-15T14:00:00',
        location: 'Lab 201, IT Building',
        location_ar: 'مختبر 201، مبنى تقنية المعلومات',
        category: 'academic',
        max_capacity: 40,
        registered_count: 32,
        status: 'published',
        cover_url: null,
        tags: ['AI', 'Machine Learning', 'Python'],
        is_featured: true,
    },
    {
        id: '2',
        title: 'Inter-College Football Tournament',
        title_ar: 'بطولة كرة القدم بين الكليات',
        description: 'Annual football tournament bringing together teams from all colleges. Register your team of 11 players and compete for the championship trophy.',
        description_ar: 'بطولة كرة القدم السنوية التي تجمع فرقاً من جميع الكليات. سجل فريقك المكون من 11 لاعباً وتنافس على كأس البطولة.',
        club_id: '2',
        club: { name: 'Sports Club', name_ar: 'النادي الرياضي' },
        date: '2026-03-20T15:00:00',
        end_date: '2026-03-20T19:00:00',
        location: 'University Football Field',
        location_ar: 'ملعب كرة القدم الجامعي',
        category: 'sports',
        max_capacity: 200,
        registered_count: 154,
        status: 'published',
        cover_url: null,
        tags: ['Football', 'Tournament', 'Sports'],
        is_featured: true,
    },
    {
        id: '3',
        title: 'Spring Art Exhibition',
        title_ar: 'معرض فن الربيع',
        description: 'Showcase student artwork ranging from paintings and sculptures to digital art. Open for submissions!',
        description_ar: 'اعرض أعمالك الفنية من لوحات ومنحوتات إلى فن رقمي. مفتوح للمشاركات!',
        club_id: '3',
        club: { name: 'Drama & Arts', name_ar: 'الدراما والفنون' },
        date: '2026-03-25T09:00:00',
        end_date: '2026-03-25T17:00:00',
        location: 'Student Center Gallery',
        location_ar: 'معرض مركز الطلاب',
        category: 'cultural',
        max_capacity: 100,
        registered_count: 67,
        status: 'published',
        cover_url: null,
        tags: ['Art', 'Exhibition', 'Culture'],
        is_featured: false,
    },
    {
        id: '4',
        title: 'Beach Cleanup Drive',
        title_ar: 'حملة تنظيف الشاطئ',
        description: 'Join us in making Salalah beaches cleaner. Supplies and refreshments provided. Let\'s make a difference!',
        description_ar: 'انضم إلينا في جعل شواطئ صلالة أنظف. الأدوات والمرطبات مقدمة. لنحدث فرقاً!',
        club_id: '4',
        club: { name: 'Volunteer Corps', name_ar: 'فيلق المتطوعين' },
        date: '2026-04-01T07:00:00',
        end_date: '2026-04-01T11:00:00',
        location: 'Al Mughsail Beach',
        location_ar: 'شاطئ المغسيل',
        category: 'community',
        max_capacity: 50,
        registered_count: 50,
        status: 'published',
        cover_url: null,
        tags: ['Volunteer', 'Environment', 'Beach'],
        is_featured: false,
    },
    {
        id: '5',
        title: 'Photography Masterclass',
        title_ar: 'دورة التصوير المتقدمة',
        description: 'Learn professional photography techniques including composition, lighting, and post-processing from award-winning photographer.',
        description_ar: 'تعلم تقنيات التصوير الاحترافي بما في ذلك التكوين والإضاءة والمعالجة اللاحقة من مصور حائز على جوائز.',
        club_id: '5',
        club: { name: 'Photography Society', name_ar: 'جمعية التصوير' },
        date: '2026-04-05T11:00:00',
        end_date: '2026-04-05T15:00:00',
        location: 'Room 105, Media Building',
        location_ar: 'قاعة 105، مبنى الإعلام',
        category: 'academic',
        max_capacity: 30,
        registered_count: 18,
        status: 'published',
        cover_url: null,
        tags: ['Photography', 'Workshop', 'Creative'],
        is_featured: true,
    },
    {
        id: '6',
        title: 'RoboChallenge 2026',
        title_ar: 'تحدي الروبوتات 2026',
        description: 'Build a robot that can navigate an obstacle course! Teams of 3-4 compete in this exciting engineering challenge.',
        description_ar: 'ابنِ روبوتاً يتجاوز مسار العقبات! فرق من 3-4 أفراد تتنافس في هذا التحدي الهندسي المثير.',
        club_id: '6',
        club: { name: 'Robotics Lab', name_ar: 'مختبر الروبوتات' },
        date: '2026-04-10T09:00:00',
        end_date: '2026-04-10T17:00:00',
        location: 'Engineering Lab, Block B',
        location_ar: 'مختبر الهندسة، المبنى ب',
        category: 'academic',
        max_capacity: 60,
        registered_count: 42,
        status: 'published',
        cover_url: null,
        tags: ['Robotics', 'Competition', 'Engineering'],
        is_featured: false,
    },
]

export const mockRegistrations = [
    { event_id: '1', status: 'confirmed', registered_at: '2026-03-01T10:00:00', attended: false },
    { event_id: '2', status: 'confirmed', registered_at: '2026-03-02T14:30:00', attended: false },
    { event_id: '5', status: 'confirmed', registered_at: '2026-03-03T09:15:00', attended: false },
]

export const mockMemberships = [
    { club_id: '1', status: 'approved', joined_at: '2025-09-15' },
    { club_id: '4', status: 'approved', joined_at: '2025-10-01' },
]

// Category color palette
export const categoryColors = {
    academic: { bg: 'bg-blue-500/15', text: 'text-blue-400', border: 'border-blue-500/30' },
    sports: { bg: 'bg-orange-500/15', text: 'text-orange-400', border: 'border-orange-500/30' },
    cultural: { bg: 'bg-purple-500/15', text: 'text-purple-400', border: 'border-purple-500/30' },
    community: { bg: 'bg-green-500/15', text: 'text-green-400', border: 'border-green-500/30' },
}

export const categoryIcons = {
    academic: '📚',
    sports: '⚽',
    cultural: '🎭',
    community: '🤝',
}

// --- Club Admin Mock Data ---

// Current club admin manages club id '1' (Tech Innovators)
export const ADMIN_CLUB_ID = '1'

export const mockMembers = [
    { id: 'm1', user_id: 'u1', club_id: '1', full_name: 'Sara Al-Habsi', full_name_ar: 'سارة الحبسي', email: 'sara@utas.edu.om', student_id: '21F1234', status: 'approved', role: 'member', joined_at: '2025-09-15', avatar_url: null },
    { id: 'm2', user_id: 'u2', club_id: '1', full_name: 'Omar Al-Rawahi', full_name_ar: 'عمر الرواحي', email: 'omar@utas.edu.om', student_id: '21F2345', status: 'approved', role: 'member', joined_at: '2025-09-20', avatar_url: null },
    { id: 'm3', user_id: 'u3', club_id: '1', full_name: 'Fatma Al-Balushi', full_name_ar: 'فاطمة البلوشي', email: 'fatma@utas.edu.om', student_id: '22F3456', status: 'approved', role: 'member', joined_at: '2025-10-01', avatar_url: null },
    { id: 'm4', user_id: 'u4', club_id: '1', full_name: 'Khalid Al-Shukri', full_name_ar: 'خالد الشكري', email: 'khalid@utas.edu.om', student_id: '22F4567', status: 'approved', role: 'member', joined_at: '2025-10-10', avatar_url: null },
    { id: 'm5', user_id: 'u5', club_id: '1', full_name: 'Aisha Al-Kindi', full_name_ar: 'عائشة الكندي', email: 'aisha@utas.edu.om', student_id: '23F5678', status: 'pending', role: 'member', joined_at: '2026-03-01', avatar_url: null },
    { id: 'm6', user_id: 'u6', club_id: '1', full_name: 'Mohammed Al-Zadjali', full_name_ar: 'محمد الزدجالي', email: 'mohammed@utas.edu.om', student_id: '23F6789', status: 'pending', role: 'member', joined_at: '2026-03-03', avatar_url: null },
    { id: 'm7', user_id: 'u7', club_id: '1', full_name: 'Layla Al-Farsi', full_name_ar: 'ليلى الفارسي', email: 'layla@utas.edu.om', student_id: '23F7890', status: 'pending', role: 'member', joined_at: '2026-03-05', avatar_url: null },
    { id: 'm8', user_id: 'u8', club_id: '1', full_name: 'Yusuf Al-Amri', full_name_ar: 'يوسف العامري', email: 'yusuf@utas.edu.om', student_id: '21F8901', status: 'rejected', role: 'member', joined_at: '2026-02-20', avatar_url: null },
]

export const mockAnnouncements = [
    {
        id: 'a1',
        club_id: '1',
        title: 'AI Workshop Preparation Guide',
        title_ar: 'دليل التحضير لورشة الذكاء الاصطناعي',
        content: 'Please install Python 3.11+ and TensorFlow before attending the AI Workshop on March 15. Bring your laptop fully charged!',
        content_ar: 'يرجى تثبيت بايثون 3.11+ وتنسرفلو قبل حضور ورشة الذكاء الاصطناعي في 15 مارس. أحضر حاسوبك مشحوناً بالكامل!',
        priority: 'high',
        created_at: '2026-03-04T10:00:00',
        author: 'Ahmed Al-Siyabi',
    },
    {
        id: 'a2',
        club_id: '1',
        title: 'New Club Meeting Schedule',
        title_ar: 'جدول اجتماعات النادي الجديد',
        content: 'Starting this month, club meetings will be held every Wednesday from 2:00 PM to 3:30 PM in Lab 201.',
        content_ar: 'بدءاً من هذا الشهر، ستُعقد اجتماعات النادي كل أربعاء من 2:00 ظهراً إلى 3:30 عصراً في مختبر 201.',
        priority: 'normal',
        created_at: '2026-03-01T14:30:00',
        author: 'Ahmed Al-Siyabi',
    },
    {
        id: 'a3',
        club_id: '1',
        title: 'Hackathon Team Registration Open',
        title_ar: 'فتح باب تسجيل فرق الهاكاثون',
        content: 'We\'re forming teams for the upcoming National Hackathon. Teams of 3-4 members. Register by March 20.',
        content_ar: 'نحن نشكل فرقاً للهاكاثون الوطني القادم. فرق من 3-4 أعضاء. سجل قبل 20 مارس.',
        priority: 'high',
        created_at: '2026-02-28T09:00:00',
        author: 'Ahmed Al-Siyabi',
    },
    {
        id: 'a4',
        club_id: '1',
        title: 'Club Photo Day',
        title_ar: 'يوم صور النادي',
        content: 'Annual club photo session this Friday. Wear your club t-shirt. Meet at the Student Center at 10 AM.',
        content_ar: 'جلسة الصور السنوية للنادي هذا الجمعة. ارتدِ قميص النادي. الالتقاء في مركز الطلاب الساعة 10 صباحاً.',
        priority: 'normal',
        created_at: '2026-02-25T11:15:00',
        author: 'Ahmed Al-Siyabi',
    },
]

export const mockAttendanceRecords = [
    { id: 'att1', event_id: '1', user_id: 'u1', full_name: 'Sara Al-Habsi', student_id: '21F1234', scanned_at: '2026-03-15T10:05:00', status: 'attended' },
    { id: 'att2', event_id: '1', user_id: 'u2', full_name: 'Omar Al-Rawahi', student_id: '21F2345', scanned_at: '2026-03-15T10:08:00', status: 'attended' },
    { id: 'att3', event_id: '1', user_id: 'u3', full_name: 'Fatma Al-Balushi', student_id: '22F3456', scanned_at: '2026-03-15T10:12:00', status: 'attended' },
    { id: 'att4', event_id: '1', user_id: 'u4', full_name: 'Khalid Al-Shukri', student_id: '22F4567', scanned_at: null, status: 'registered' },
]

export const mockAnalyticsData = {
    attendanceTrend: [
        { month: 'Oct', month_ar: 'أكتوبر', attendance: 28, capacity: 40 },
        { month: 'Nov', month_ar: 'نوفمبر', attendance: 35, capacity: 45 },
        { month: 'Dec', month_ar: 'ديسمبر', attendance: 22, capacity: 30 },
        { month: 'Jan', month_ar: 'يناير', attendance: 40, capacity: 50 },
        { month: 'Feb', month_ar: 'فبراير', attendance: 38, capacity: 40 },
        { month: 'Mar', month_ar: 'مارس', attendance: 32, capacity: 40 },
    ],
    memberGrowth: [
        { month: 'Oct', month_ar: 'أكتوبر', members: 42 },
        { month: 'Nov', month_ar: 'نوفمبر', members: 51 },
        { month: 'Dec', month_ar: 'ديسمبر', members: 58 },
        { month: 'Jan', month_ar: 'يناير', members: 67 },
        { month: 'Feb', month_ar: 'فبراير', members: 76 },
        { month: 'Mar', month_ar: 'مارس', members: 85 },
    ],
    eventsByCategory: [
        { category: 'Workshop', category_ar: 'ورشة عمل', count: 8 },
        { category: 'Hackathon', category_ar: 'هاكاثون', count: 3 },
        { category: 'Seminar', category_ar: 'ندوة', count: 5 },
        { category: 'Social', category_ar: 'اجتماعي', count: 4 },
    ],
    topEvents: [
        { name: 'AI Workshop 2026', name_ar: 'ورشة الذكاء الاصطناعي', registered: 32, attended: 28, rate: 87.5 },
        { name: 'Web Dev Bootcamp', name_ar: 'معسكر تطوير الويب', registered: 45, attended: 38, rate: 84.4 },
        { name: 'Cybersecurity Talk', name_ar: 'محاضرة الأمن السيبراني', registered: 30, attended: 22, rate: 73.3 },
        { name: 'Python Workshop', name_ar: 'ورشة بايثون', registered: 40, attended: 35, rate: 87.5 },
    ],
}

// --- System Admin Mock Data ---

export const mockUsers = [
    { id: 'u-admin1', full_name: 'Dr. Ahmed Al-Siyabi', full_name_ar: 'د. أحمد السيابي', email: 'ahmed.admin@utas.edu.om', student_id: null, role: 'system_admin', status: 'active', created_at: '2025-08-01', avatar_url: null },
    { id: 'u-ca1', full_name: 'Noor Al-Busaidi', full_name_ar: 'نور البوسعيدي', email: 'noor@utas.edu.om', student_id: '20F0001', role: 'club_admin', status: 'active', created_at: '2025-08-10', avatar_url: null, club_name: 'Tech Innovators' },
    { id: 'u-ca2', full_name: 'Hassan Al-Lawati', full_name_ar: 'حسن اللواتي', email: 'hassan@utas.edu.om', student_id: '20F0002', role: 'club_admin', status: 'active', created_at: '2025-08-12', avatar_url: null, club_name: 'Sports Club' },
    { id: 'u1', full_name: 'Sara Al-Habsi', full_name_ar: 'سارة الحبسي', email: 'sara@utas.edu.om', student_id: '21F1234', role: 'student', status: 'active', created_at: '2025-09-15', avatar_url: null },
    { id: 'u2', full_name: 'Omar Al-Rawahi', full_name_ar: 'عمر الرواحي', email: 'omar@utas.edu.om', student_id: '21F2345', role: 'student', status: 'active', created_at: '2025-09-20', avatar_url: null },
    { id: 'u3', full_name: 'Fatma Al-Balushi', full_name_ar: 'فاطمة البلوشي', email: 'fatma@utas.edu.om', student_id: '22F3456', role: 'student', status: 'active', created_at: '2025-10-01', avatar_url: null },
    { id: 'u4', full_name: 'Khalid Al-Shukri', full_name_ar: 'خالد الشكري', email: 'khalid@utas.edu.om', student_id: '22F4567', role: 'student', status: 'active', created_at: '2025-10-10', avatar_url: null },
    { id: 'u5', full_name: 'Aisha Al-Kindi', full_name_ar: 'عائشة الكندي', email: 'aisha@utas.edu.om', student_id: '23F5678', role: 'student', status: 'active', created_at: '2026-03-01', avatar_url: null },
    { id: 'u6', full_name: 'Mohammed Al-Zadjali', full_name_ar: 'محمد الزدجالي', email: 'mohammed@utas.edu.om', student_id: '23F6789', role: 'student', status: 'disabled', created_at: '2025-11-05', avatar_url: null },
    { id: 'u7', full_name: 'Layla Al-Farsi', full_name_ar: 'ليلى الفارسي', email: 'layla@utas.edu.om', student_id: '23F7890', role: 'student', status: 'active', created_at: '2026-01-10', avatar_url: null },
    { id: 'u8', full_name: 'Yusuf Al-Amri', full_name_ar: 'يوسف العامري', email: 'yusuf@utas.edu.om', student_id: '21F8901', role: 'student', status: 'active', created_at: '2025-09-25', avatar_url: null },
    { id: 'u9', full_name: 'Maryam Al-Hinai', full_name_ar: 'مريم الهنائي', email: 'maryam@utas.edu.om', student_id: '22F9012', role: 'student', status: 'active', created_at: '2025-10-20', avatar_url: null },
    { id: 'u10', full_name: 'Ali Al-Maskari', full_name_ar: 'علي المسكري', email: 'ali@utas.edu.om', student_id: '23F0123', role: 'student', status: 'active', created_at: '2026-02-15', avatar_url: null },
]

export const mockPendingClubs = [
    {
        id: 'pc1',
        name: 'Coding Ninjas',
        name_ar: 'نينجا البرمجة',
        description: 'A competitive programming club focused on algorithmic problem solving, coding contests, and interview preparation.',
        description_ar: 'نادي البرمجة التنافسية يركز على حل المسائل الخوارزمية ومسابقات البرمجة والتحضير للمقابلات.',
        category: 'academic',
        requested_by: 'Salim Al-Hashmi',
        requested_by_ar: 'سالم الهاشمي',
        requested_at: '2026-03-02',
        status: 'pending',
        member_count: 0,
    },
    {
        id: 'pc2',
        name: 'Debate Society',
        name_ar: 'جمعية المناظرات',
        description: 'Enhancing public speaking and critical thinking through structured debates, Model UN simulations, and rhetoric workshops.',
        description_ar: 'تعزيز الخطابة والتفكير النقدي من خلال المناظرات المنظمة ومحاكاة نموذج الأمم المتحدة وورش الخطابة.',
        category: 'cultural',
        requested_by: 'Huda Al-Riyami',
        requested_by_ar: 'هدى الريامي',
        requested_at: '2026-03-04',
        status: 'pending',
        member_count: 0,
    },
]

export const mockPlatformStats = {
    totalUsers: 248,
    activeEvents: 12,
    totalClubs: 8,
    pendingApprovals: 2,
    totalRegistrations: 863,
    avgEventAttendance: 78,
    monthlyActivity: [
        { month: 'Oct', month_ar: 'أكتوبر', users: 120, events: 5, registrations: 180 },
        { month: 'Nov', month_ar: 'نوفمبر', users: 145, events: 7, registrations: 245 },
        { month: 'Dec', month_ar: 'ديسمبر', users: 160, events: 4, registrations: 150 },
        { month: 'Jan', month_ar: 'يناير', users: 195, events: 8, registrations: 320 },
        { month: 'Feb', month_ar: 'فبراير', users: 220, events: 10, registrations: 380 },
        { month: 'Mar', month_ar: 'مارس', users: 248, events: 12, registrations: 420 },
    ],
    usersByRole: [
        { role: 'Students', role_ar: 'طلاب', count: 230 },
        { role: 'Club Admins', role_ar: 'مدراء أندية', count: 12 },
        { role: 'System Admins', role_ar: 'مدراء النظام', count: 6 },
    ],
}
